-- Seed data for PokeMap
-- Generated from pokemon.csv, korea_living_areas.csv, and pokemon_db.csv
-- Run after migrations: supabase db seed (during `supabase db reset`)

-- Pokemon Regions (8 regions)
INSERT INTO pokemon_regions (id, name) VALUES
  (1, '관동지방'),
  (2, '성도지방'),
  (3, '호연지방'),
  (4, '신오지방'),
  (5, '하나지방'),
  (6, '칼로스지방'),
  (7, '알로라지방'),
  (8, '가라르지방')
ON CONFLICT DO NOTHING;

-- Provinces (17 도, extracted from pokemon.csv and korea_living_areas.csv)
INSERT INTO provinces (id, name, region_id, is_island_endgame) VALUES
  (1, '서울특별시', 1, false),
  (2, '부산광역시', 3, false),
  (3, '대구광역시', 8, false),
  (4, '인천광역시', 1, false),
  (5, '광주광역시', 8, false),
  (6, '대전광역시', 5, false),
  (7, '울산광역시', 3, false),
  (8, '세종특별자치시', 5, false),
  (9, '경기도', 1, false),
  (10, '강원도', 4, false),
  (11, '충청북도', 2, false),
  (12, '충청남도', 5, false),
  (13, '전라북도', 6, false),
  (14, '전라남도', 8, false),
  (15, '경상북도', 8, false),
  (16, '경상남도', 3, false),
  (17, '제주도', 7, true)
ON CONFLICT DO NOTHING;

-- Living Areas + Cities (색상 및 시군별)
-- Data structure: living_areas(id, province_id, name, color) + cities(id, living_area_id, name, centroid, is_legendary_site)
-- Note: This seed file is generated by build_pokemon_db.py → python script conversion
-- For production use, run: python build_pokemon_db.py && psql -d <db> -f <generated_seed>.sql
-- Placeholder: detailed city/living_area/spawn_pool data should be inserted here

-- TODO: Auto-generate from build_pokemon_db.py output
-- Temporary: Will be populated by deployment script
